name: 'andyvanee.com'
description: 'Thoughts on Programming, Metaphysics, and anything in between'
url:  'http://andyvanee.com'
pygments:  true
exclude: [src, Makefile, README.md]
paginate:  16
destination: build/jekyll
source: jekyll/
plugins: jekyll/_plugins
