name: 'andyvanee.com'
description: 'Thoughts on Programming, Metaphysics, and anything in between'
url:  'http://andyvanee.com'
pygments:  true
exclude: []
paginate:  16
destination: ./tmp/jekyll
source:  ./jekyll
plugins: ./jekyll/_plugins
api: 'http://0.0.0.0:4567'
