baseURL = "https://www.andyvanee.com/"
languageCode = "en-us"
title = "andyvanee"
theme = "andyvanee"
summaryLength = 30
publishDir = "docs"
[permalinks]
posts = "/:year/:month/:day/:title"
[markup.goldmark.renderer]
    unsafe = true
[pagination]
pagerSize = 9